package com.madiv;

public class Index {
	public static void main(String[] args) {
		System.out.println("01. Some code helped in development in Bravura Solutions	:	com.madiv.brv");
		System.out.println("02. Dynamic property reader, load property value in run time : com.madiv.dynamicprops");
		System.out.println("03. Some regex example including greedy regex :	com.madiv.regex");
		System.out.println("04. Java 8 Stream and Filters : com.madiv.learning");
		System.out.println("05. Encrypting Decrypting password using BouncyCastle API : com.madiv.pwd");
		System.out.println("06. Java JMX beans : com.madiv.jmx");
		System.out.println("07. AWS SQS client sending and receiving SQS message : com.madiv.sqs");
		System.out.println("08. Jackson API to read and write JSON objects : com.madiv.jackson");
		System.out.println("09. JAVA Generic as box : com.madiv.generic.box => SenderClient.java");
		System.out.println("    Class Diagram : ClassDiagram.ucls");
		System.out.println("10. Spring basic annotation based : com.madiv.spring");
		System.out.println("11. Spring AOP annotation based : com.madiv.spring.aop");
		System.out.println("12. Free Marker template : com.madiv.freemarker");
		System.out.println("13. java Base64 encoding and decoding messages : com.madiv.crypto.decode => EncoderDecoderClient.java");
		System.out.println("14. Public Private key generator (propbably not completed) : com.madiv.crypto.keypair => PublicPrivateKeyClient.java");
		System.out.println("15. HmacSHA1 using hashkey : com.madiv.crypto.sha1 => Sha1HashCreator.java");
		System.out.println("16. Understanding StringBuilder and writing meta program to process 3.1 million record to write shell script: com.madiv.strbuilder");
		System.out.println("17. [April 24, 2019] : Affirm : FileSystemWatcher to know if any operation is being done on that folder : com.madiv.filesystemwatcher");
		System.out.println("18. [Jun 19, 2019] : Affirm : Compare logs generated by backup_single_schemaRds.sh two days : com.madiv.schema.rds.log.analyzer");
		System.out.println("19. [Sep 09, 2019] : Affirm : Rest client calling rest API : com.madiv.rest");
		System.out.println("20. [Apr 08, 2020] : Affirm : Read CSV and convert JSON for API, main class CSV2JSonConverter.java : com.madiv.jsonapi");
		System.out.println("21. [Apr 08, 2020] : USing OpenCSV to read CSV file : com.madiv.opencsv.OpenCSVSimpleClient.java");
		System.out.println("22. [May 02, 2020] : Using object mapper to convert objects to json or map : com.madiv.objectmapper");
		System.out.println("23. [Feb 16, 2021] : Beatify JSON using gson api : com.madiv.gson");
		
	}
}
